#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
#PS1='[\u@\h \W]\$ '
PS1="\e[30;44m[\u@\h \w]\e[0m\n\$ "
#PS1="\e[34m[\u@\h \w]\e[0m\n\$ "

eval `dircolors`

