#
format = """
$username\
$hostname\
$directory\
$cmd_duration\
$line_break\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

[hostname]
ssh_only = true
format = '[$hostname]($style) '
style = 'bold green'

[username]
show_always = false
format = '[$user]($style)@'
style_user = 'bold green'

[directory]
truncation_length = 10
truncation_symbol = '…/'
truncate_to_repo = false

[cmd_duration]
min_time = 5000
format = '\[[⏱ $duration]($style)\]'

